# Generated by Django 4.2.2 on 2023-06-25 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(default='', max_length=100)),
                ('tempat_lahir', models.CharField(default='', max_length=100)),
                ('tanggal_lahir', models.DateField(default=datetime.date.today)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='', max_length=1)),
                ('lembaga', models.CharField(default='', max_length=100)),
                ('nomor_induk', models.CharField(default='', max_length=20)),
                ('jurusan', models.CharField(default='', max_length=100)),
                ('kelas', models.CharField(choices=[('X', 'X SEPULUH'), ('XI', 'XI SEBELAS'), ('XII', 'XII DUA BELAS')], default='', max_length=100)),
                ('rombel', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
