# Generated by Django 4.2.2 on 2023-06-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode_images/'),
        ),
    ]
