# Generated by Django 4.2.2 on 2023-06-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_siswa_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='barcode_image',
        ),
    ]
