# Generated by Django 4.2.2 on 2023-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_remove_siswa_barcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_guru', models.CharField(max_length=100, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('nuptk', models.CharField(max_length=100)),
                ('nomer_hp', models.CharField(max_length=100)),
            ],
        ),
    ]
