# Generated by Django 4.2.2 on 2023-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0005_pelanggaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='point_pelanggaran',
            field=models.CharField(default='', max_length=255),
        ),
    ]
