# Generated by Django 4.2.2 on 2023-07-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelanggaranSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_siswa', models.CharField(default='', max_length=100)),
                ('nama_pelanggaran', models.CharField(default='', max_length=100)),
                ('point_pelanggaran', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
