# Generated by Django 4.2.2 on 2023-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0008_pelanggaransiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='siswa/qr_codes'),
        ),
    ]
