# Generated by Django 4.2.2 on 2023-07-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0010_tindakan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaTindakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
                ('tindakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.tindakan')),
            ],
        ),
        migrations.CreateModel(
            name='SiswaPelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.pelanggaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
        ),
    ]
