# Generated by Django 4.2.2 on 2023-08-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0012_delete_pelanggaransiswa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswapelanggaran',
            name='tindakan_list',
        ),
        migrations.AddField(
            model_name='tindakan',
            name='id_tindakan',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='siswapelanggaran',
            name='pelanggaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siswa.pelanggaran'),
        ),
    ]
