# Generated by Django 4.2.2 on 2023-08-10 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0013_remove_siswapelanggaran_tindakan_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswapelanggaran',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
